# Generated by Django 2.2.6 on 2019-10-29 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=100)),
                ('image_path', models.CharField(max_length=600)),
                ('description', models.TextField()),
                ('author', models.CharField(max_length=100)),
                ('end_time', models.DateTimeField(auto_now_add=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
