# Generated by Django 2.2.6 on 2019-10-29 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='test',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
    ]
