# Generated by Django 2.2.6 on 2019-10-29 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_team_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='create_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
